CREATE TABLE SCA_data(
    page_number                 SMALLINT        NOT NULL    UNIQUE,
    defendant_address           VARCHAR(225),
    defendant_name              VARCHAR(255), 
    case_status                 VARCHAR(25), 
    filling_date                DATE, 
    close_date                  DATE, 
    case_summary                VARCHAR(2000), 
    Exchange_Act_1934           boolean, 
    Act_1933                    boolean, 
    "10b5"                      boolean, 
    Derivative                  boolean, 
    IPO                         boolean, 
    Secondary_Offering          boolean, 
    Bankruptcy                  boolean, 
    False_misleading            boolean, 
    Failed_disclose             boolean, 
    Commissions                 boolean, 
    Fees                        boolean, 
    Accounting                  boolean, 
    Conflicts_Interest          boolean, 
    Corporate_Governance        boolean, 
    "10Q_Filling"               boolean, 
    "10K_Filling"               boolean, 
    Press_Release               boolean, 
    Second_Quarter              boolean, 
    Third_Quarter               boolean, 
    Fourth_Quarter              boolean, 
    Customers                   boolean, 
    Net_Income                  boolean, 
    Revenue_Rec                 boolean, 
    Cash_Flow                   boolean, 
    Stock_Drop                  boolean, 
    Heavy_trading               boolean,
    Sector                      VARCHAR(25), 
    Industry                    VARCHAR(25), 
    Symbol                      VARCHAR(25), 
    Status_2                    VARCHAR(25), 
    Headquarters                VARCHAR(225), 
    Company_market              VARCHAR(25), 
    Court                       VARCHAR(25), 
    Docket                      VARCHAR(25), 
    Judge                       VARCHAR(25), 
    Date_Filed                  DATE, 
    Class_Period_Start          DATE, 
    Class_Period_End            DATE, 
    Plaintiff_firm              VARCHAR(2225),
    PRIMARY KEY (page_number)
);

CREATE TABLE customer(
    name VARCHAR(25),
    address VARCHAR(80)
);
